// Auto-generated by scripts/generate-items.js. Do not edit manually.
// Official CEFR writing-production descriptor per level, used as the AI marking rubric anchor.

import type { CEFRLevel } from './items';

export const WRITING_RUBRICS: Record<CEFRLevel, string> = {
  A1: 'Can produce simple isolated phrases and sentences.',
  A2: 'Can produce a series of simple phrases and sentences linked with simple connectors like "and", "but" and "because".',
  B1: 'Can produce straightforward connected texts on a range of familiar subjects within their field of interest, by linking a series of shorter discrete elements into a linear sequence.',
  B2: 'Can produce clear, detailed texts on a variety of subjects related to their field of interest, synthesising and evaluating information and arguments from a number of sources.',
  C1: 'Can produce clear, well-structured texts of complex subjects, underlining the relevant salient issues, expanding and supporting points of view at some length with subsidiary points, reasons and relevant examples, and rounding off with an appropriate conclusion.',
  C2: 'Can produce clear, smoothly flowing, complex texts in an appropriate and effective style and a logical structure which helps the reader identify significant points.',
};
